// Builds the policy editor into one self-contained HTML document, then emits
// it as a TS string module for the studio MCP route to serve as a ui://
// resource. Hosts block remote fonts and fetch, so nothing may load from a URL.
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { gzipSync } from 'node:zlib';
import tailwindcss from '@tailwindcss/postcss';
import { defineConfig } from 'vite';
import { viteSingleFile } from 'vite-plugin-singlefile';
import {
  escapeScriptClose,
  selfContainedProblems,
} from './src/self-contained.ts';

const root = dirname(fileURLToPath(import.meta.url));
const outDir = join(root, '../../dist/apps/policy-editor-mcp-app');
const htmlModule = join(root, 'generated/app-html.ts');

/** Escapes `</script` in every chunk before it is inlined. */
const escapeScriptCloseInChunks = () => ({
  name: 'policy-editor:escape-script-close',
  renderChunk: (code) => ({ code: escapeScriptClose(code), map: null }),
});

/** Checks the inlined HTML and writes it as `POLICY_EDITOR_APP_HTML`. */
const emitHtmlModule = () => ({
  name: 'policy-editor:emit-html-module',
  writeBundle(_options, bundle) {
    const asset = bundle['index.html'];
    const html = asset?.type === 'asset' ? String(asset.source) : '';
    const problems = html ? selfContainedProblems(html) : ['no index.html'];
    if (problems.length) {
      this.error(
        `policy editor HTML is not self-contained: ${problems.join('; ')}`,
      );
    }

    mkdirSync(dirname(htmlModule), { recursive: true });
    writeFileSync(
      htmlModule,
      '// Generated by `nx run policy-editor-mcp-app:build`. Do not edit or commit.\n' +
        `export const POLICY_EDITOR_APP_HTML: string = ${JSON.stringify(html)};\n`,
    );
    const bytes = Buffer.byteLength(html);
    const gzip = gzipSync(html).length;
    console.log(
      `policy editor HTML: ${bytes} bytes (${gzip} gzip) -> ${htmlModule}`,
    );
  },
});

export default defineConfig({
  root,
  css: { postcss: { plugins: [tailwindcss()] } },
  build: {
    outDir,
    emptyOutDir: true,
    target: 'es2022',
    // Everything is inlined, so there is nothing to preload.
    modulePreload: { polyfill: false },
    sourcemap: false,
    reportCompressedSize: false,
  },
  plugins: [escapeScriptCloseInChunks(), viteSingleFile(), emitHtmlModule()],
});
