// Builds the policy editor into one self-contained HTML document, then emits
// it as a TS string module for the studio MCP route to serve as a ui://
// resource. Hosts block remote fonts and fetch, so nothing may load from a URL.
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { gzipSync } from 'node:zlib';
import tailwindcss from '@tailwindcss/postcss';
import { defineConfig } from 'vite';
import { viteSingleFile } from 'vite-plugin-singlefile';

const root = dirname(fileURLToPath(import.meta.url));
const outDir = join(root, '../../dist/apps/policy-editor-mcp-app');
const htmlModule = join(root, 'generated/app-html.ts');

/** Escapes every `</script`, in any case, so inlined JS cannot end its tag. */
const escapeScriptClose = () => ({
  name: 'policy-editor:escape-script-close',
  renderChunk: (code) => ({
    code: code.replace(/<\/(script)/gi, '<\\/$1'),
    map: null,
  }),
});

/** Why `html` is not self-contained; empty when it is. */
const selfContainedProblems = (html) => {
  const problems = [];
  const opens = html.match(/<script\b/gi)?.length ?? 0;
  const closes = html.match(/<\/script/gi)?.length ?? 0;
  if (opens !== closes) problems.push('an inlined script contains </script');

  const styles = [...html.matchAll(/<style\b[^>]*>([\s\S]*?)<\/style>/gi)];
  const css = styles.map((match) => match[1]).join('\n');
  const markup = html
    .replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, '<script></script>')
    .replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, '<style></style>');

  if (/<link\b/i.test(markup)) problems.push('a <link> survived inlining');
  if (/\s(?:src|href|srcset|poster|action)\s*=/i.test(markup)) {
    problems.push('the markup references a URL');
  }
  for (const [, url] of css.matchAll(/url\(\s*['"]?([^'")\s]+)/gi)) {
    if (!url.startsWith('data:') && !url.startsWith('#')) {
      problems.push(`the CSS loads ${url}`);
    }
  }
  if (/@import\b/i.test(css)) problems.push('the CSS has an @import');
  if (!css.includes('data:font/woff2;base64,')) {
    problems.push('the Monlam font is not inlined');
  }
  return problems;
};

/** Checks the inlined HTML and writes it as `POLICY_EDITOR_APP_HTML`. */
const emitHtmlModule = () => ({
  name: 'policy-editor:emit-html-module',
  writeBundle(_options, bundle) {
    const asset = bundle['index.html'];
    const html = asset?.type === 'asset' ? String(asset.source) : '';
    const problems = html ? selfContainedProblems(html) : ['no index.html'];
    if (problems.length) {
      this.error(
        `policy editor HTML is not self-contained: ${problems.join('; ')}`,
      );
    }

    mkdirSync(dirname(htmlModule), { recursive: true });
    writeFileSync(
      htmlModule,
      '// Generated by `nx run policy-editor-mcp-app:build`. Do not edit or commit.\n' +
        `export const POLICY_EDITOR_APP_HTML: string = ${JSON.stringify(html)};\n`,
    );
    const bytes = Buffer.byteLength(html);
    const gzip = gzipSync(html).length;
    console.log(
      `policy editor HTML: ${bytes} bytes (${gzip} gzip) -> ${htmlModule}`,
    );
  },
});

export default defineConfig({
  root,
  css: { postcss: { plugins: [tailwindcss()] } },
  build: {
    outDir,
    emptyOutDir: true,
    target: 'es2022',
    // Everything is inlined, so there is nothing to preload.
    modulePreload: { polyfill: false },
    sourcemap: false,
    reportCompressedSize: false,
  },
  plugins: [escapeScriptClose(), viteSingleFile(), emitHtmlModule()],
});
