module.exports = {
  theme: {
    extend: {
      colors: {
        sidebar: {
          DEFAULT: 'rgba(var(--sidebar-background))',
          foreground: 'rgba(var(--sidebar-foreground))',
          primary: 'rgba(var(--sidebar-primary))',
          'primary-foreground': 'rgba(var(--sidebar-primary-foreground))',
          accent: 'rgba(var(--sidebar-accent))',
          'accent-foreground': 'rgba(var(--sidebar-accent-foreground))',
          border: 'rgba(var(--sidebar-border))',
          ring: 'rgba(var(--sidebar-ring))',
        },
        popover: {
          DEFAULT: 'rgba(var(--color-background))',
        },
        background: 'rgba(var(--color-background))',
        primary: 'rgba(var(--color-primary))',
        'primary-foreground': 'rgba(var(--color-primary-lightest))',
        secondary: 'rgba(var(--color-secondary))',
        'secondary-foreground': 'rgba(var(--color-secondary-lightest))',
        success: 'rgba(var(--color-success))',
        warning: 'rgba(var(--color-warning))',
        error: 'rgba(var(--color-error))',
        border: 'rgba(var(--color-border))',
        lightgray: 'rgba(var( --color-lightgray))',
        surface: 'rgb(var(--color-surface-lightest))',
        bodytext: 'rgb(var(--color-bodytext))',
        dark: 'rgb(var(--color-dark))',
        link: 'rgb(var(--color-link))',
        darkborder: 'rgb(var(--color-darkborder))',
        darkgray: 'rgb(var(--color-darkgray))',
        destructive: 'rgb(var(--color-error))',
        'destructive-foreground': 'rgb(var(--color-lighterror))',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
