import { type NextRequest, NextResponse } from 'next/server';
import { updateSession } from '@eightyfourthousand/data-access/ssr';

// Studio routes config (generated by next.config.js at startup)
// Falls back to empty config if file doesn't exist
type StudioRoutesConfig = {
  publicRoutes: string[];
  restrictedRoutes: Record<string, string[]>;
};

let studioRoutes: StudioRoutesConfig = {
  publicRoutes: [],
  restrictedRoutes: {},
};
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const mod = require('./config/studio-routes.json');
  studioRoutes = mod.default ?? mod;
} catch {
  // File doesn't exist - use empty defaults
}

// /mcp does its own bearer-token auth; /.well-known serves public OAuth
// discovery metadata; /oauth/authorize is the consent screen, which handles
// the signed-out state itself so the authorization_id survives login.
// None of these use cookie sessions, so all must bypass the login redirect.
const BASE_PUBLIC_ROUTES = [
  '/login',
  '/auth',
  '/mcp',
  '/.well-known',
  '/oauth/authorize',
];
const BASE_RESTRICTED_ROUTES: Record<string, string[]> = {
  '/publications/editor': ['admin', 'editor', 'translator'],
  '/project': ['admin', 'editor', 'translator'],
};

// Merge base routes with studio config routes
const PUBLIC_ROUTES = [...BASE_PUBLIC_ROUTES, ...studioRoutes.publicRoutes];
const RESTRICTED_ROUTE_ROLES: Record<string, string[]> = {
  ...BASE_RESTRICTED_ROUTES,
  ...studioRoutes.restrictedRoutes,
};
const RESTRICTED_ROUTES = Object.keys(RESTRICTED_ROUTE_ROLES);

/**
 * Marks a response as uncacheable.
 *
 * Both redirects below are decided from the request's cookies, but the platform
 * default for a redirect out of here is `Cache-Control: public` with no
 * `Vary: Cookie` — so any cache in the path may serve one user's auth decision
 * to everyone asking for that URL. Safari reuses such a redirect far more
 * readily than Chrome, which is why deep links failed there and why appending a
 * trailing slash (a different cache key) appeared to fix them.
 */
function noStore(response: NextResponse): NextResponse {
  response.headers.set('Cache-Control', 'no-store');
  return response;
}

export async function proxy(request: NextRequest) {
  const { user, role, supabaseResponse } = await updateSession(request);

  const pathname = request.nextUrl.pathname;

  const isKnowledgeBase = pathname.startsWith('/knowledgebase');
  if (isKnowledgeBase) {
    return NextResponse.redirect(new URL(pathname, 'https://84000.co'));
  }

  const isPublicRoute = PUBLIC_ROUTES.some((route) =>
    pathname.startsWith(route),
  );

  if (!user && !isPublicRoute) {
    // no user, potentially respond by redirecting the user to the login page
    const url = request.nextUrl.clone();
    url.pathname = '/login';
    // Carry the requested URL through login so a deep link survives the
    // round-trip. `authCallback` already reads `next`; nothing set it before,
    // so anyone opening an /entity/... link signed out landed on the homepage
    // and lost the entity they clicked.
    url.search = '';
    url.searchParams.set('next', `${pathname}${request.nextUrl.search}`);
    return noStore(NextResponse.redirect(url));
  }

  // IMPORTANT: You *must* return the supabaseResponse object as it is.
  // If you're creating a new response object with NextResponse.next() make sure to:
  // 1. Pass the request in it, like so:
  //    const myNewResponse = NextResponse.next({ request })
  // 2. Copy over the cookies, like so:
  //    myNewResponse.cookies.setAll(supabaseResponse.cookies.getAll())
  // 3. Change the myNewResponse object to fit your needs, but avoid changing
  //    the cookies!
  // 4. Finally:
  //    return myNewResponse
  // If this is not done, you may be causing the browser and server to go out
  // of sync and terminate the user's session prematurely!

  const restrictedRoute = RESTRICTED_ROUTES.find((route) =>
    pathname.startsWith(route),
  );
  const isRestrictedRoute = !!restrictedRoute;
  const hasRequiredRole = isRestrictedRoute
    ? RESTRICTED_ROUTE_ROLES[restrictedRoute]?.includes(role)
    : true;

  if (isRestrictedRoute && !hasRequiredRole) {
    const url = request.nextUrl.clone();
    url.pathname = '/not-found';
    const redirect = noStore(NextResponse.redirect(url));
    const cookies = supabaseResponse.cookies.getAll();
    cookies.forEach((cookie) => {
      redirect.cookies.set(cookie.name, cookie.value, cookie);
    });
    return redirect;
  }

  return supabaseResponse;
}

export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     * - icon and apple-touch-icon files
     */
    '/((?!_next/static|_next/image|favicon.ico|icon.png|apple-touch-icon.png|apple-touch-icon-precomposed.png|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)',
  ],
};
