/**
 * Map database annotation types (kebab-case) to GraphQL enum values
 */
export const ANNOTATION_DTO_TYPE_TO_ENUM: Record<string, string> = {
  abbreviation: 'ABBREVIATION',
  audio: 'AUDIO',
  blockquote: 'BLOCKQUOTE',
  code: 'CODE',
  'deprecated-internal-link': 'DEPRECATED',
  'end-note-link': 'END_NOTE_LINK',
  'glossary-instance': 'GLOSSARY_INSTANCE',
  'has-abbreviation': 'HAS_ABBREVIATION',
  heading: 'HEADING',
  image: 'IMAGE',
  indent: 'INDENT',
  'inline-title': 'INLINE_TITLE',
  'internal-link': 'INTERNAL_LINK',
  'leading-space': 'LEADING_SPACE',
  line: 'LINE',
  'line-group': 'LINE_GROUP',
  link: 'LINK',
  list: 'LIST',
  'list-item': 'LIST_ITEM',
  mantra: 'MANTRA',
  paragraph: 'PARAGRAPH',
  quote: 'QUOTE',
  quoted: 'QUOTED',
  reference: 'REFERENCE',
  span: 'SPAN',
  table: 'TABLE',
  'table-body-data': 'TABLE_BODY_DATA',
  'table-body-header': 'TABLE_BODY_HEADER',
  'table-body-row': 'TABLE_BODY_ROW',
  trailer: 'TRAILER',
  unknown: 'UNKNOWN',
};
