import Image from 'next/image';
import React from 'react';
import { Button } from '@design-system';
import Link from 'next/link';
import type { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Error-404',
  description: 'Generated by create next app',
};
const Error = () => {
  return (
    <>
      <div className="h-screen flex items-center justify-center bg-white dark:bg-darkgray">
        <div className="text-center max-w-lg mx-auto">
          <Image
            width={500}
            height={500}
            src={'/images/backgrounds/errorimg.svg'}
            alt="error"
            className="mb-4"
          />
          <h1 className="text-dark dark:text-white text-4xl mb-6">Opps!!!</h1>
          <h6 className="text-xl text-dark dark:text-white">
            This page you are looking for could not be found.
          </h6>
          <Button variant={'link'} className="w-fit mt-6 mx-auto">
            <Link href="/">Go Back to Home</Link>
          </Button>
        </div>
      </div>
    </>
  );
};

export default Error;
