import React from 'react';
import { Button, H2, H5, MiniLogo } from '@design-system';
import Link from 'next/link';
import type { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Error-404',
  description: 'Generated by create next app',
};
const Error = () => {
  return (
    <>
      <div className="h-screen flex items-center justify-center bg-white dark:bg-darkgray">
        <div className="text-center mx-auto">
          <div className="flex justify-center mb-6">
            <MiniLogo width={100} height={100} />
          </div>
          <H2 className="text-slate mb-6">Oops!!!</H2>
          <H5 className="text-slate">
            This page you are looking for could not be found.
          </H5>
          <Button variant={'link'} className="w-fit mt-6 mx-auto">
            <Link href="/">Go Back to Home</Link>
          </Button>
        </div>
      </div>
    </>
  );
};

export default Error;
