import { Imprint } from '@data-access';
import { TranslationSkeleton } from './TranslationSkeleton';
import { LabeledElement } from './LabeledElement';
import { H2 } from '@design-system';

export const ImprintTab = ({ imprint }: { imprint?: Imprint }) => {
  if (!imprint) {
    return <TranslationSkeleton />;
  }

  const { license, version, publishYear, publisherStatement } = imprint;

  return (
    <LabeledElement label="im.">
      <H2>Imprint</H2>
      <div className="flex flex-col gap-5 text-center text-muted-foreground">
        {publishYear && <p>First published {publishYear}</p>}
        {version && <p>Current version v {version}</p>}
        {publisherStatement && <p>{publisherStatement}</p>}
        {license.description && <p>{license.description}</p>}
        <p>Generated by the Scholar's Room</p>
      </div>
    </LabeledElement>
  );
};
