import { Imprint as ImprintData } from '@data-access';
import { TranslationSkeleton } from './TranslationSkeleton';
import { SectionTitle } from '@design-system';

export const Imprint = ({ imprint }: { imprint?: ImprintData }) => {
  if (!imprint) {
    return <TranslationSkeleton />;
  }

  const { license, version, publishYear, publisherStatement } = imprint;

  return (
    <div id="imprint">
      <SectionTitle>Imprint</SectionTitle>
      <div className="flex flex-col mt-4 mx-auto max-w-xl gap-5 text-center text-xs text-foreground/75">
        {publishYear && <p>First published {publishYear}</p>}
        {version && <p>Current version v {version}</p>}
        {publisherStatement && <p>{publisherStatement}</p>}
        {license.description && <p>{license.description}</p>}
        <p>Generated by the Scholar's Room</p>
      </div>
    </div>
  );
};
